### ISSUE TITLE
meta issue: Sesame workbench -- jetty distribition -- SPARQL endpoint

### ISSUE THREAD

**Issue by ghxiao** [ontop/ontop#84]
This issue is a meta issue. It is used for collecting current issues related to the ontop extension of Sesame workbench and SPARQL endpoint
- [x] The current sesame workbench used in Ontop is based on Sesame 2.7, while latest sesame workbench is based on Sesame 4 (#68)
- [x] Jetty 8 -> Jetty 9
- [x] It is known that under Tomcat,  the JDBC drivers cannot be found
- [x] Packing issue: some configuration  is hard-code in the jetty distribution but not in the code base
- [ ] On Windows, when inputing owl/obda filename, one has to use '/' in the path. '\' will lead to error
- [ ] The user-supplied-key optimization is not exposed in this jetty configuration (#139)
- [x] R2RML is not supported directly. One needs to convert it to .obda file via command line.

**Comment by dockstreet** [comment]
Is this still the plan? Can Ontop be used in a later rdf4j release by just including the Ontop wars/jars?

**Comment by bcogrel** [comment]
Not supported anymore since 4.1.0.
